services:
  postgres:
    image: postgres:15
    container_name: guildhub_postgres
    environment:
      POSTGRES_DB: guildhub-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guildhub_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: guildhub_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/guildhub-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      MINIO_ENDPOINT: http://minio:9000
    networks:
      - guildhub_network

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: guildhub_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - guildhub_network

volumes:
  postgres_data:
  minio_data:

networks:
  guildhub_network:
    driver: bridge