spring:
  application:
    name: guildhub
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/guildhub-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  server:
    port: 8080

jwt:
  secret: guildhub-secret-key-for-jwt-token-generation-change-this-in-production-123456789012345678901234567890
  access_token_expiration: 86400000

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  buckets:
    avatars: guildhub-avatars
    videos: guildhub-videos

logging:
  level:
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    liquibase: DEBUG